-- 024_preview_proxy_url.sql
-- Lightweight streamable preview proxies for the creative library.
--
-- Problem: lib_creative_library.preview_url points at the FULL raw upload —
-- e.g. 1.48 GB non-faststart Sony XAVC camera files. Playing those inline is
-- extremely slow (huge bitrate, moov atom at the end), and they show a black
-- screen while the first frame loads. The originals must stay for download.
--
-- Fix: store a small faststart H.264 proxy (~15 MB, 720p) per clip. The player
-- streams the proxy for instant inline playback; downloads still use the
-- original (final_cut_url > drive_url > preview_url). Generated by
-- scripts/transcode-proxies.mjs (ffmpeg) — backfill + on every new upload.
--
-- thumbnail_url already exists (migration 011); the transcoder also fills it
-- with a poster frame when missing, which kills the black-on-load flash.

ALTER TABLE lib_creative_library
  ADD COLUMN IF NOT EXISTS preview_proxy_url TEXT;

COMMENT ON COLUMN lib_creative_library.preview_proxy_url IS
  'Small faststart 720p H.264 proxy for fast inline playback. NULL = not yet '
  'transcoded; player falls back to preview_url. Originals stay for download.';

NOTIFY pgrst, 'reload schema';
