-- 025_submission_preview_proxy.sql
-- Streamable preview proxies for editor SUBMISSIONS (the same fix as 024,
-- now for lib_task_submissions).
--
-- Problem: lib_task_submissions.file_url is the editor's raw uploaded cut.
-- The queue + review modals play it directly, so big files stream slowly and
-- the 15 live submissions with no thumbnail_url show a black screen on load.
--
-- Fix: store a small faststart 720p H.264 proxy per submission. The player
-- streams the proxy for instant inline playback; download still uses file_url.
-- Generated by scripts/transcode-proxies.mjs --table submissions (ffmpeg) —
-- backfill + on every new upload. The transcoder also fills thumbnail_url with
-- a poster frame when missing, killing the black-on-load flash.

ALTER TABLE lib_task_submissions
  ADD COLUMN IF NOT EXISTS preview_proxy_url TEXT;

COMMENT ON COLUMN lib_task_submissions.preview_proxy_url IS
  'Small faststart 720p H.264 proxy for fast inline playback of the editor '
  'submission. NULL = not yet transcoded; player falls back to file_url.';

NOTIFY pgrst, 'reload schema';
